# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PodPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PodPod

pod 'HexColors'
pod 'Hero', '1.0.0-alpha.4'

end
